import React from "react";
import { BrowserRouter as Switch, Route } from "react-router-dom";

import Home from "./home";
import Games from "./games";

import * as pages from "../storages/content";

export default function routePages() {
  return (
    <Switch>
      <Route exact path="/" component={Home} />
      <Route exact path="/games" component={Games} />
      <></>
      <Route
        exact
        path="/mi-van-du-trend-tiktok-voi-bao-ngu-con-gai-sap-thanh-thieu-nu-ma-sao-chi-khong-chiu-gia-di-mot-xiu"
        component={pages.page_20210604043337}
      />
      <Route
        exact
        path="/thanh-nu-dota-2-mung-tuoi-moi-chieu-dai-fan-bang-bo-anh-khoe-vong-mot-cuc-pham-tren-instagram"
        component={pages.page_20210604043413}
      />
      <Route
        exact
        path="/so-lo-noi-y-se-bi-phat-nu-streamer-outplay-bang-cach-khong-mac-buoc-ao-ho-hung-che-vong-mot"
        component={pages.page_20210604043529}
      />
      <Route
        exact
        path="/viet-tus-tha-thinh-tao-bao-nu-streamer-goi-cam-khang-dinh-dung-nhin-ve-ngoai-danh-dong-tat-ca"
        component={pages.page_20210604043625}
      />
      <Route
        exact
        path="/ninh-duong-lan-ngoc-dien-bikini-khoe-body-nong-hon-ngay-he-ai-ngo-luot-xuong-doi-chan-te-ngang-vi-chi-tiet-nay"
        component={pages.page_20210604043806}
      />
      <Route
        exact
        path="/gai-xinh-noi-tieng-voi-loat-vlog-tren-o-to-khoe-anh-qua-bao-phai-zoom-sat-rat-vong-1-moi-chiu"
        component={pages.page_20210604043950}
      />
      <Route
        exact
        path="/hoa-khoi-tiep-vien-hang-khong-buoc-vao-dai-hoi-sexy-voi-vong-1-cang-day-lap-lo"
        component={pages.page_20210604044036}
      />
      <Route
        exact
        path="/lan-ngoc-da-khoe-anh-dien-do-boi-nong-bong-don-he-tien-the-cho-be-mo-di-choi-cung-cho-vui"
        component={pages.page_20210604044125}
      />
      <Route
        exact
        path="/loat-khoanh-khac-quen-tat-camera-tren-song-va-cac-su-co-kho-do-cua-nhung-nu-streamer-noi-tieng"
        component={pages.page_20210604044225}
      />
      <Route
        exact
        path="/ghim-ngay-nhung-cau-noi-truyen-cam-hung-trong-haikyuu-de-dech-so-gi-het-ma-tien-len"
        component={pages.page_20210604044318}
      />
      <Route
        exact
        path="/dau-truong-chan-ly-leo-top-la-de-voi-nhung-doi-hinh-tap-hop-nhung-wonder-woman-cuc-manh-o-mua-5"
        component={pages.page_20210604044331}
      />
      <Route
        exact
        path="/chia-tay-ban-trai-my-nhan-nhat-ban-lang-lang-nop-don-dang-ky-lam-dien-vien-18"
        component={pages.page_20210604044342}
      />
      <Route
        exact
        path="/kham-pha-thi-truong-quang-cao-game-nua-dau-nam-2021"
        component={pages.page_20210604044355}
      />
      <Route
        exact
        path="/chap-nhan-khong-mac-ao-de-quang-cao-san-pham-nu-streamer-lien-quan-chinh-thuc-lap-ky-luc-ve-su-nong-bong-cua-minh"
        component={pages.page_20210604044426}
      />

      <Route
        exact
        path="/no-nan-chong-chat-lua-ca-tien-fan-nu-streamer-xinh-dep-tuyen-bo-cung-duong-dong-phim-18-de-tra-no"
        component={pages.page_20210603065007}
      />
      <Route
        exact
        path="/bi-che-gieu-vi-nang-toi-1-ta-nu-youtuber-giam-30kg-than-toc-lot-xac-goi-cam-toi-kho-tin"
        component={pages.page_20210603065223}
      />
      <Route
        exact
        path="/dai-gia-duc-huy-lo-hint-du-lich-voi-tinh-tre-kem-27-tuoi-chinh-la-dia-diem-tuyen-bo-khong-co-em-anh-co-em-khac"
        component={pages.page_20210603065324}
      />

      <Route
        exact
        path="/atomi-shuri-chan-nghiep-dien-vien-nguoi-dep-18-bat-ngo-giai-nghe-khien-fan-ngo-ngang"
        component={pages.page_202106030443}
      />

      <Route
        exact
        path="/tai-ngay-game-turn-based-cuc-dinh-warhammer-quest-silver-tower-mien-phi-100"
        component={pages.page_20210603053727}
      />

      <Route
        exact
        path="/2-game-mien-phi-cho-playstation-4-trong-thang-6"
        component={pages.page_202106030700}
      />
      <Route
        exact
        path="/he-lo-ket-cau-cot-truyen-cua-game-thuan-viet-300475"
        component={pages.page_20210603054034}
      />
      <Route
        exact
        path="/3-cpu-gia-re-duoi-2-trieu-nhung-van-choi-game-ngon-ma-khong-can-card-do-hoa"
        component={pages.page_20210603054155}
      />
      <Route
        exact
        path="/nhung-tua-game-hay-nhat-trong-10-nam-qua-theo-binh-chon-cua-game-thu"
        component={pages.page_20210603054326}
      />
      <Route
        exact
        path="/ken-shimizu-chi-ra-doi-tac-loi-hai-nhat-tung-gap-khien-anh-chang-phai-dau-hang-chi-sau-3-phut-khong-dam-dong-cung-lan-hai"
        component={pages.page_20210603054509}
      />
      <Route
        exact
        path="/hot-girl-co-khuon-nguc-hon-1m-bat-ngo-tiet-lo-tin-soc-dang-xa-tri-ung-thu-xin-cu-dan-mang-ngung-body-shaming"
        component={pages.page_20210603054621}
      />
      <Route
        exact
        path="/dau-truong-chan-ly-hoc-hoi-nhung-meo-doc-khi-choi-sett-one-punch-man-tu-ky-thu-top-8-thach-dau"
        component={pages.page_202106021159}
      />
      <Route
        exact
        path="/linh-chichan-dien-trang-phuc-tha-rong-toi-90-vong-mot-nu-streamer-viet-nhan-ve-nhieu-y-kien-trai-chieu"
        component={pages.page_202106030950}
      />
      <Route
        exact
        path="/ngoc-trinh-vo-tu-dang-clip-chinh-sua-noi-y-de-lo-ca-do-bao-ho-ben-trong-nhin-ma-thot-tim"
        component={pages.page_202106021319}
      />
      <Route
        exact
        path="/vu-thi-anh-thu-lo-anh-thoi-chua-phau-thuat-tham-my"
        component={pages.page_202106011900}
      />
      <Route
        exact
        path="/sam-bi-tuot-bikini-tren-song-nu-youtuber-voi-vang-che-day-nhung-van-ho-henh-len-tieng-tran-tinh-tai-vong-mot-qua-to"
        component={pages.page_202106021031}
      />
      <Route
        exact
        path="/one-piece-du-da-chet-nhung-suc-manh-cua-6-nhan-vat-huyen-thoai-nay-cho-den-nay-van-chua-ai-vuot-qua-noi"
        component={pages.page_202106021223}
      />
      <Route
        exact
        path="/hop-tac-hang-xe-mclaren-pubg-mobile-tung-event-hap-dan-sieu-toc-bac-nhat-lang-game-thang-6"
        component={pages.page_202106020330}
      />
      <Route
        exact
        path="/ngoc-trinh-trinh-lang-bst-noi-y-bi-to-dao-nhai-victorias-secret-thiet-ke-va-gia-ro-the-nao"
        component={pages.page_202106031010}
      />
      <Route
        exact
        path="/gau-kami-nu-streamer-gan-7-trieu-luot-follow-tiktok-bi-gia-mao-tai-khoan-hang-loat-tham-chi-bi-loi-dung-hinh-anh-de-lua-dao"
        component={pages.page_202106030305}
      />
    </Switch>
  );
}
